<a href="https://colab.research.google.com/github/Palakds/Palakds/blob/main/Numpy_lec_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating Numpy Arrays

In [2]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2D and 3D
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# dtype
p=np.array([1,2,3],dtype=float)
print(type(p))

<class 'numpy.ndarray'>


In [8]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# with reshape
np.arange(1,11).reshape(5,2)   #matrix of 5 rows 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
#np.ones and np.zeros
np.ones((3,4))   #ones means each item is one


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#np.random
np.random.random((3,4))

array([[0.88374141, 0.32823896, 0.11041331, 0.65661111],
       [0.15592753, 0.11150623, 0.94716912, 0.3915757 ],
       [0.90514089, 0.27303728, 0.14934775, 0.51464044]])

In [15]:
#np.linspace   #linearly space
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [16]:
#np.identity
np.identity(3)  #default is flaot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Atrributes

In [18]:
a1=np.arange(10)  #simple 1d array vector
a2=np.arange(12,dtype=float).reshape(3,4)   #2d matrix
a3=np.arange(8).reshape(2,2,2)   #3d tensor
a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
#ndim (dimension)
a1.ndim
a2.ndim

2

In [22]:
#shape
a1.shape
a2.shape

(3, 4)

In [25]:
#size (no. of times kitne hai)
print(a3.size)
a3

8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
#itemsize (harr item memory mein kitna size occupy kr rha hai )
a3.itemsize

8

In [28]:
#dtype (items ka data type)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## Changing datatype

In [30]:
#astype  (change the space occupied by memory)
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array operations

In [37]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
#scalar operation
#arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [39]:
# Realtional operators
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
#vector multiplication
#arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Function

In [43]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[66., 35., 16.],
       [ 6., 26.,  4.],
       [ 8.,  6., 80.]])

In [45]:
# max/min/sum/prod
np.sum(a1)
np.max(a1)
#0=column and 1=row
np.max(a1,axis=1)

array([66., 26., 80.])

In [47]:
#mean/median/std/var
np.mean(a1)
np.mean(a1,axis=1)

array([39.        , 12.        , 31.33333333])

In [48]:
#trigo function
np.sin(a1)

array([[-0.02655115, -0.42818267, -0.28790332],
       [-0.2794155 ,  0.76255845, -0.7568025 ],
       [ 0.98935825, -0.2794155 , -0.99388865]])

In [51]:
#dot product  (multiplication of matrix)
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [53]:
#log and exponents
np.exp(a1)
np.log(a1)

array([[4.18965474, 3.55534806, 2.77258872],
       [1.79175947, 3.25809654, 1.38629436],
       [2.07944154, 1.79175947, 4.38202663]])

In [56]:
#round/floor/ceil
np.floor(np.random.random((2,3))*100)

array([[40., 22.,  8.],
       [64., 32., 35.]])

## Indexing nad slicing

In [77]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a1

[-1]

In [63]:
a1[0]

0

In [78]:
a1[-1]

9

In [65]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
# pop out 6
a2[1,2]  #row,column

6

In [67]:
a2[1,0]

4

In [68]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
a3[1,0,1]  # treat 3d as 2d then 2d row and column

5

In [71]:
a3[0,1,0]

2

In [79]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Slicing

In [80]:
a1[2:5]   #last wala is not included in slicing

array([2, 3, 4])

In [81]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a2[0,:]  #colon for all columns

array([0, 1, 2, 3])

In [83]:
a2[:,2]

array([ 2,  6, 10])

In [84]:
a2[1:,1:3]   #colon is basically for onwards

array([[ 5,  6],
       [ 9, 10]])

In [85]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [86]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [89]:
a2[1,::3]

array([4, 7])

In [91]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [92]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
a3 = np.arange(27).reshape(3,3,3)

In [94]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [96]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
a3[0,1]

array([3, 4, 5])

In [99]:
a3[1,:,1]

array([10, 13, 16])

In [101]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [105]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [106]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [110]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [114]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [115]:
for i in np.nditer(a3):    #converted into 1 d and printed the items
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [118]:
#transpose
a2
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [120]:
#ravel(convert into 1d)
a2.ravel()
a3.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [122]:
#horizontal stacking    (shape must be same)
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [124]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [125]:
# vertical stacking  (data ko combine krke analysis krna ho)
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [ ]:
#horizontal and vertical splitting
#opposite of stacking

In [127]:
a4
np.hsplit(a4,2)  #how many equal part which is 2 in this case

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [128]:
np.hsplit(a4,4)   #has to be equal division

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [129]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [130]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]