<a href="https://colab.research.google.com/github/Palakds/Palakds/blob/main/Numpy_tricks_lec_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[77, 13, 52, 13],
       [99, 60, 74, 42],
       [50, 17, 36, 60],
       [98, 71, 46, 98],
       [64, 92, 29, 71],
       [72, 14, 14, 22]])

In [6]:
np.sort(a)
#for desc order
np.sort(a)[::-1]

array([97, 93, 91, 91, 89, 85, 82, 75, 61, 57, 51, 50, 42, 28, 13])

In [5]:
np.sort(b,axis=0)

array([[50, 13, 14, 13],
       [64, 14, 29, 22],
       [72, 17, 36, 42],
       [77, 60, 46, 60],
       [98, 71, 52, 71],
       [99, 92, 74, 98]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
#code
np.append(a,100)

array([ 57,  91,  28,  91,  13,  89,  85,  82,  75,  51,  97,  61,  50,
        93,  42, 100])

In [8]:
b

array([[77, 13, 52, 13],
       [99, 60, 74, 42],
       [50, 17, 36, 60],
       [98, 71, 46, 98],
       [64, 92, 29, 71],
       [72, 14, 14, 22]])

In [9]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[77., 13., 52., 13.,  1.],
       [99., 60., 74., 42.,  1.],
       [50., 17., 36., 60.,  1.],
       [98., 71., 46., 98.,  1.],
       [64., 92., 29., 71.,  1.],
       [72., 14., 14., 22.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [11]:
#code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [14]:
#code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [19]:
#code
a
a.shape

(15,)

In [17]:
np.expand_dims(a,axis=0)

array([[57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42]])

In [18]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [20]:
np.expand_dims(a,axis=1)

array([[57],
       [91],
       [28],
       [91],
       [13],
       [89],
       [85],
       [82],
       [75],
       [51],
       [97],
       [61],
       [50],
       [93],
       [42]])

In [21]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [22]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [23]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  5,  6,  7,  8,  9, 10, 11, 13]),)

In [24]:
#replace all value > 50 with 0
#np.where(condition,replace,s it is)
np.where(a>50,0,a)

array([ 0,  0, 28,  0, 13,  0,  0,  0,  0,  0,  0,  0, 50,  0, 42])

In [25]:
# replace all even number with 0
np.where(a%2 == 0,0,a)

array([57, 91,  0, 91, 13, 89, 85,  0, 75, 51, 97, 61,  0, 93,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [26]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [27]:
np.argmax(a)  #index position

10

In [28]:
b

array([[77, 13, 52, 13],
       [99, 60, 74, 42],
       [50, 17, 36, 60],
       [98, 71, 46, 98],
       [64, 92, 29, 71],
       [72, 14, 14, 22]])

In [30]:
np.argmax(b,axis=0)

array([1, 4, 1, 3])

In [31]:
#np.argmin
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [32]:
np.argmin(a)

4

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [33]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [34]:
np.cumsum(a)

array([  57,  148,  176,  267,  280,  369,  454,  536,  611,  662,  759,
        820,  870,  963, 1005])

In [35]:
np.cumsum(b)

array([  77,   90,  142,  155,  254,  314,  388,  430,  480,  497,  533,
        593,  691,  762,  808,  906,  970, 1062, 1091, 1162, 1234, 1248,
       1262, 1284])

In [36]:
np.cumsum(b,axis=0)

array([[ 77,  13,  52,  13],
       [176,  73, 126,  55],
       [226,  90, 162, 115],
       [324, 161, 208, 213],
       [388, 253, 237, 284],
       [460, 267, 251, 306]])

In [37]:
#np.cumprod
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [38]:
np.cumprod(a)

array([                  57,                 5187,               145236,
                   13216476,            171814188,          15291462732,
              1299774332220,      106581495242040,     7993612143153000,
         407674219300803000,  2650911124758787768, -4315118053099910696,
        5605026229519084592,  4758605281407421808, -3052762991693351840])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [39]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [40]:
np.percentile(a,100)

97.0

In [41]:
np.percentile(a,0)

13.0

In [42]:
np.percentile(a,50)

75.0

In [43]:
np.median(a)

75.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [44]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [45]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 1, 0, 1, 3, 1, 1, 3, 4]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [46]:
np.histogram(a,bins=[0,50,100])

(array([ 3, 12]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [47]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [48]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [50]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([50])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [51]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [52]:
np.flip(a)

array([42, 93, 50, 61, 97, 51, 75, 82, 85, 89, 13, 91, 28, 91, 57])

In [54]:
b

array([[77, 13, 52, 13],
       [99, 60, 74, 42],
       [50, 17, 36, 60],
       [98, 71, 46, 98],
       [64, 92, 29, 71],
       [72, 14, 14, 22]])

In [53]:
np.flip(b)   # rowwise and column wise flip

array([[22, 14, 14, 72],
       [71, 29, 92, 64],
       [98, 46, 71, 98],
       [60, 36, 17, 50],
       [42, 74, 60, 99],
       [13, 52, 13, 77]])

In [55]:
np.flip(b,axis=0)

array([[72, 14, 14, 22],
       [64, 92, 29, 71],
       [98, 71, 46, 98],
       [50, 17, 36, 60],
       [99, 60, 74, 42],
       [77, 13, 52, 13]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [56]:
a

array([57, 91, 28, 91, 13, 89, 85, 82, 75, 51, 97, 61, 50, 93, 42])

In [57]:
np.put(a,[0,1],[110,530])   #permanent changes

In [58]:
a

array([110, 530,  28,  91,  13,  89,  85,  82,  75,  51,  97,  61,  50,
        93,  42])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [59]:
a

array([110, 530,  28,  91,  13,  89,  85,  82,  75,  51,  97,  61,  50,
        93,  42])

In [61]:
np.delete(a,0)

array([530,  28,  91,  13,  89,  85,  82,  75,  51,  97,  61,  50,  93,
        42])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [62]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
np.intersect1d(m,n)

array([3, 4, 5])

In [64]:
np.setdiff1d(n,m)

array([6, 7])

In [65]:
np.setxor1d(m,n)   #common ko hata dega baki ko rakh lega

array([1, 2, 6, 7])

In [70]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [66]:
m[np.in1d(m,1)]   #check krta hai item hai ki nhi

array([1])

In [69]:
m[np.in1d(m,10)]

array([], dtype=int64)

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [67]:
a

array([110, 530,  28,  91,  13,  89,  85,  82,  75,  51,  97,  61,  50,
        93,  42])

In [68]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 75, 25, 75, 75, 75, 75, 51, 75, 61, 50, 75, 42])